global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "financial_rag_api"
    static_configs:
      - targets: ["api:8000"]
    metrics_path: "/metrics"

  - job_name: "qdrant"
    static_configs:
      - targets: ["qdrant:6333"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
